### ISSUE TITLE
string.gsub in utils function M.replace_line_content throwing multiple annoying errors

### ISSUE THREAD

**Issue by mAmineChniti** [fedepujol/bracketpair.nvim#5]
This error keeps popping up in nvim whenever i move the cursor around, i found what's causing it and will be submitting a PR for your consideration.

![WindowsTerminal_8erI1tZyCH](https://github.com/fedepujol/bracketpair.nvim/assets/124379229/d4d4a7fb-1951-49b3-8d79-b4608e0a1670)

**Comment by fedepujol** [comment]
Hey! I've been on a trip for the last few days, thanks for the PR but I've notice you closed it.

I'll check the changes and merge it!

**Comment by mAmineChniti** [comment]
@fedepujol hope you had a good trip i mistakenly thought this project wasn't maintained anymore, my PR fixes a part of the problem but not the whole problem itself, the amount of errors defintely gets much less but not a 0

**Comment by fedepujol** [comment]
Merged! Will check the other errors out
